# Makefile.deps created Sun Oct 27 22:43:26 PDT 2013 by /Applications/Xcode.app/Contents/Developer/usr/bin/make
astree.o: astree.cc astree.h auxlib.h stringset.h lyutils.h yyparse.h
lyutils.o: lyutils.cc lyutils.h astree.h auxlib.h yyparse.h
auxlib.o: auxlib.cc auxlib.h
stringset.o: stringset.cc stringset.h auxlib.h
yylex.o: yylex.cc auxlib.h lyutils.h astree.h yyparse.h
yyparse.o: yyparse.cc auxlib.h lyutils.h astree.h yyparse.h
